services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fixpunkt\FpNewsletter\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/{Domain/Model,Utility}'

  Fixpunkt\FpNewsletter\Backend\EventListener\PreviewEventListener:
    tags:
      - name: "event.listener"
        identifier: 'fp_newsletter/preview-rendering'

  Fixpunkt\FpNewsletter\Command\ImportFEUsersScheduler:
    tags:
      - name: "console.command"
        command: "fp_newsletter:importfeusers"
        description: "Import newsletter-subscriber from tt_address for Luxletter"